import typing


class JosephProtocolType:
    def set(self, name: str, value: typing.Any) -> None: ...
    def get(self, name: str, default: typing.Any|None=None) -> typing.Any: ...
    def saveData(self) -> None: ...



class _SettingsType:
    DEBUG: bool

    WINDOW_WIDTH: int
    WINDOW_HEIGHT: int
    WINDOW_MINWIDTH: int
    WINDOW_MINHEIGHT: int

    JOSEPH: JosephProtocolType

    SHOW_INFO: bool

    OS_PLATFORM: str






class _RequestType:
    def closeGame(self) -> None: ...
    def setFps(self, fps) -> None: ...

    def redirectScene(self, scene: str) -> None: ...
    def restartScene(self) -> None: ...


class _WindowApiType:
    def setGrab(self, grab_flag: bool) -> None: ...
    def setVsync(self, vsync_mode: int) -> None: ...
    def setRelative(self, rel_flag: bool) -> None: ...
    def clearColor(self, r: float, g: float, b: float) -> None: ...

    def setWindowPos(self, x: int, y: int) -> None: ...
    def setWindowSize(self, w: int, h: int) -> None: ...
    def setWindowMinlimit(self, min_x: int, min_y: int) -> None: ...
    def setTitle(self, title: str) -> None: ...


class _EventApiType:
    def isMinimilized(self, event) -> bool: ...
    def isMaximilized(self, event) -> bool: ...
    def isRestored(self, event) -> bool: ...
    def isResized(self, event) -> bool: ...
    def isFocusLost(self, event) -> bool: ...
    def isFocusGain(self, event) -> bool: ...


class _SystemApiType:
    def openUrl(self, url: str) -> None: ...
    def chooseFile(self, message: str) -> str: ...
    def createMsgBox(self, title: str, info: str, type_messagebpx: int=0) -> None: ...
    




class _PathsType:
    def getConfigPath(self, *folder: str, file: str) -> str: ...
    def getCsavesPath(self, *folder: str, file: str) -> str: ...
    def getMusicsPath(self, *folder: str, file: str) -> str: ...
    def getSoundsPath(self, *folder: str, file: str) -> str: ...
    def getAssetsPath(self, *folder: str, file: str) -> str: ...
    def getImagesPath(self, *folder: str, file: str) -> str: ...
    def getFontsPath(self, *folder: str, file: str) -> str: ...
    def getShadersPath(self, *folder: str, file: str) -> str: ...
    


class _LoggerType:
    def trace(message: str) -> None: ...
    





class _Keyboard:
    def isPressDown(self, key: int, event) -> bool: ...
    def isPressUp(self, key: int, event) -> bool: ...
    def isPress(self, key: int) -> bool: ...

class _Mouse:
    def mouseEnter(self, event) -> bool: ...
    def mouseLeave(self, event) -> bool: ...
    def mouseButtonDown(self, button: int, event) -> bool: ...
    def mouseButtonUp(self, button: int, event) -> bool: ...

    def isLeft(self) -> bool: ...
    def isMiddle(self) -> bool: ...  
    def isRight(self) -> bool: ...

    def getPos(self) -> tuple[float, float]: ...
    def getRel(self) -> tuple[float, float]: ...
    def getWheel(self) -> float: ...



class GameType(typing.Protocol):
    config_api: _RequestType
    window_api: _WindowApiType
    event_api: _EventApiType
    system_api: _SystemApiType

    settings: _SettingsType
    paths: _PathsType
    logger: _LoggerType

    delta_time: float
    tick_time: float

    keyboard: _Keyboard
    mouse: _Mouse

    PROJECT_NAME: str
    ERROR: str

    def getFps(self) -> float: ...
    def getTps(self) -> float: ...
    def getCurrentScene(self) -> str: ...
    def raiseError(self) -> None: ...







