[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rudlgc"
version = "0.1.0"
description = "Daemon`s RUDL Game Core Engine"
authors = [
  { name="DaemonDuck", email="simulasimulasimula15@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "pysdl2==0.9.17",
  "pysdl2-dll==2.32.0", 
  "moderngl==5.12.0", 
  "PyGLM==2.8.3",
  "platformdirs==4.9.4",
  "pyinstaller",
  "easygui==0.98.3"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["rudlgc*"]

[tool.setuptools.package-data]
"rudlgc" = [
  "stuff/**/*"
]

[project.scripts]
rudlgc-admin = "rudlgc.core.execute_prompt:_rudlgc_admin"
