import sdl2


class Keysym:
    A = sdl2.SDL_SCANCODE_A
    W = sdl2.SDL_SCANCODE_W
    S = sdl2.SDL_SCANCODE_S
    D = sdl2.SDL_SCANCODE_D

    B = sdl2.SDL_SCANCODE_B
    C = sdl2.SDL_SCANCODE_C
    D = sdl2.SDL_SCANCODE_D
    E = sdl2.SDL_SCANCODE_E
    F = sdl2.SDL_SCANCODE_F
    G = sdl2.SDL_SCANCODE_G
    H = sdl2.SDL_SCANCODE_H
    I = sdl2.SDL_SCANCODE_I
    J = sdl2.SDL_SCANCODE_J
    K = sdl2.SDL_SCANCODE_K
    L = sdl2.SDL_SCANCODE_L
    M = sdl2.SDL_SCANCODE_M
    N = sdl2.SDL_SCANCODE_N
    O = sdl2.SDL_SCANCODE_O
    P = sdl2.SDL_SCANCODE_P
    Q = sdl2.SDL_SCANCODE_Q
    R = sdl2.SDL_SCANCODE_R
    T = sdl2.SDL_SCANCODE_T
    U = sdl2.SDL_SCANCODE_U
    V = sdl2.SDL_SCANCODE_V
    X = sdl2.SDL_SCANCODE_X
    Y = sdl2.SDL_SCANCODE_Y
    Z = sdl2.SDL_SCANCODE_Z

    SPACE = sdl2.SDL_SCANCODE_SPACE
    ENTER = sdl2.SDL_SCANCODE_RETURN
    ESC = sdl2.SDL_SCANCODE_ESCAPE
    TAB = sdl2.SDL_SCANCODE_TAB
    CAPS = sdl2.SDL_SCANCODE_CAPSLOCK

    BACKSPACE = sdl2.SDL_SCANCODE_BACKSPACE
    DELETE = sdl2.SDL_SCANCODE_DELETE
    INSERT = sdl2.SDL_SCANCODE_INSERT
    HOME = sdl2.SDL_SCANCODE_HOME
    END = sdl2.SDL_SCANCODE_END
    PAGEUP = sdl2.SDL_SCANCODE_PAGEUP
    PAGEDOWN = sdl2.SDL_SCANCODE_PAGEDOWN

    SHIFT = sdl2.SDL_SCANCODE_LSHIFT
    CTRL = sdl2.SDL_SCANCODE_LCTRL
    ALT = sdl2.SDL_SCANCODE_LALT
    
    RSHIFT = sdl2.SDL_SCANCODE_RSHIFT
    RCTRL = sdl2.SDL_SCANCODE_RCTRL
    RALT = sdl2.SDL_SCANCODE_RALT

    
    UP = sdl2.SDL_SCANCODE_UP
    DOWN = sdl2.SDL_SCANCODE_DOWN
    LEFT = sdl2.SDL_SCANCODE_LEFT
    RIGHT = sdl2.SDL_SCANCODE_RIGHT

    NUM_1 = sdl2.SDL_SCANCODE_1
    NUM_2 = sdl2.SDL_SCANCODE_2
    NUM_3 = sdl2.SDL_SCANCODE_3
    NUM_4 = sdl2.SDL_SCANCODE_4
    NUM_5 = sdl2.SDL_SCANCODE_5
    NUM_6 = sdl2.SDL_SCANCODE_6
    NUM_7 = sdl2.SDL_SCANCODE_7
    NUM_8 = sdl2.SDL_SCANCODE_8
    NUM_9 = sdl2.SDL_SCANCODE_9
    NUM_0 = sdl2.SDL_SCANCODE_0

    KP_0 = sdl2.SDL_SCANCODE_KP_0
    KP_1 = sdl2.SDL_SCANCODE_KP_1
    KP_2 = sdl2.SDL_SCANCODE_KP_2
    KP_3 = sdl2.SDL_SCANCODE_KP_3
    KP_4 = sdl2.SDL_SCANCODE_KP_4
    KP_5 = sdl2.SDL_SCANCODE_KP_5
    KP_6 = sdl2.SDL_SCANCODE_KP_6
    KP_7 = sdl2.SDL_SCANCODE_KP_7
    KP_8 = sdl2.SDL_SCANCODE_KP_8
    KP_9 = sdl2.SDL_SCANCODE_KP_9

    KP_PLUS = sdl2.SDL_SCANCODE_KP_PLUS
    KP_MINUS = sdl2.SDL_SCANCODE_KP_MINUS
    KP_MULTIPLY = sdl2.SDL_SCANCODE_KP_MULTIPLY
    KP_DIVIDE = sdl2.SDL_SCANCODE_KP_DIVIDE
    KP_ENTER = sdl2.SDL_SCANCODE_KP_ENTER
    KP_DOT = sdl2.SDL_SCANCODE_KP_DECIMAL

    F1 = sdl2.SDL_SCANCODE_F1
    F2 = sdl2.SDL_SCANCODE_F2
    F3 = sdl2.SDL_SCANCODE_F3
    F4 = sdl2.SDL_SCANCODE_F4
    F5 = sdl2.SDL_SCANCODE_F5
    F6 = sdl2.SDL_SCANCODE_F6
    F7 = sdl2.SDL_SCANCODE_F7
    F8 = sdl2.SDL_SCANCODE_F8
    F9 = sdl2.SDL_SCANCODE_F9
    F10 = sdl2.SDL_SCANCODE_F10
    F11 = sdl2.SDL_SCANCODE_F11
    F12 = sdl2.SDL_SCANCODE_F12


class Mouse:
    LEFT = sdl2.SDL_BUTTON_LEFT
    MIDDLE = sdl2.SDL_BUTTON_MIDDLE
    RIGHT = sdl2.SDL_BUTTON_RIGHT


